SELECT * FROM MARK WHERE MARK>6 ORDER BY MARK DESC;
SELECT * FROM PAYMENT WHERE AMOUNT < 300 ORDER BY AMOUNT ASC;
SELECT name FROM PAYMENTTYPE  ORDER BY NAME ASC;
SELECT name FROM STUDENT ORDER BY NAME DESC;
SELECT DISTINCT  STUDENT.NAME  FROM STUDENT INNER JOIN PAYMENT ON  STUDENT.ID =PAYMENT.STUDENT_ID  WHERE AMOUNT >1000 ORDER BY BIRTHDAY ASC