INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES ('John',  '2022-01-15',1);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES ('Chris', '2022-01-15',1);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES ('Carl', '2022-01-15',1);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES  ('Oliver', '2022-01-15',2);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES  ('James', '2022-01-15',2);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES ('Lucas', '2022-01-15',2);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES  ('Henry', '2022-01-15',2);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES   ('Jacob', '2022-01-15',3);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES   ('Logan', '2022-01-15',3);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES   ('Mary', '2022-01-15',4);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES   ('Ann', '2022-01-15',4);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES   ('Lola', '2022-01-15',5);
INSERT INTO Student (name, BIRTHDAY , GROUPNUMBER  ) VALUES   ('Iris', '2022-01-15',5);
INSERT INTO Subject (name, grade) VALUES ('Art', 1);
INSERT INTO Subject (name, grade) VALUES ('Music', 1);
INSERT INTO Subject (name, grade) VALUES ('Geography',2);
INSERT INTO Subject (name, grade) VALUES ('History',2);
INSERT INTO Subject (name, grade) VALUES ('PE',3);
INSERT INTO Subject (name, grade) VALUES ('Math',3);
INSERT INTO Subject (name, grade) VALUES ( 'Science',4);
INSERT INTO Subject (name, grade) VALUES ( 'IT',4);
INSERT INTO Subject (name, grade) VALUES ('Literature',5);
INSERT INTO Subject (name, grade) VALUES ( 'Geometry',5);
INSERT INTO PaymentType (name) VALUES ('DAILY');
INSERT INTO PaymentType (name) VALUES ('WEEKLY');
INSERT INTO PaymentType (name) VALUES  ( 'MONTHLY');
INSERT INTO Payment (type_id,  amount, payment_date, student_id) VALUES ( 2, 1000, '2022-01-15',1 );
INSERT INTO Payment (type_id,  amount, payment_date, student_id) VALUES ( 3, 2000, '2022-01-15',4);
INSERT INTO Payment (type_id,  amount, payment_date, student_id) VALUES ( 2, 3000, '2022-01-15',7);
INSERT INTO Payment (type_id,  amount, payment_date, student_id) VALUES ( 1, 4000, '2022-01-15',5);
INSERT INTO Payment (type_id,  amount, payment_date, student_id) VALUES ( 2,  500, '2022-01-15',6);
INSERT INTO Mark (student_id, subject_id, mark) VALUES ( 2, 1, 8);
INSERT INTO Mark (student_id, subject_id, mark) VALUES ( 4, 4, 5);
INSERT INTO Mark (student_id, subject_id, mark) VALUES ( 5, 3, 9);
INSERT INTO Mark (student_id, subject_id, mark) VALUES ( 8, 6, 4);
INSERT INTO Mark (student_id, subject_id, mark) VALUES (9, 5, 9);
INSERT INTO Mark (student_id, subject_id, mark) VALUES (7, 8, 8);
