ALTER TABLE Student ALTER birthday DATE NOT NULL;
ALTER TABLE Mark ALTER subject_id BIGINT NOT NULL;
ALTER TABLE Mark ADD CONSTRAINT CH_MARK CHECK (mark >=1 AND mark<=10);
ALTER TABLE Subject ADD CONSTRAINT CH_grade CHECK (grade>=1 AND grade<=5);
ALTER TABLE PaymentType ADD CONSTRAINT UN_name UNIQUE(name);
ALTER TABLE Payment ALTER type_id BIGINT NOT NULL;
ALTER TABLE Payment ALTER  amount DECIMAL NOT NULL;
ALTER TABLE Payment ALTER payment_date DATETIME NOT NULL;