ALTER TABLE Student ALTER birthday DATE NOT NULL;
ALTER TABLE Mark MODIFY subject_id BIGINT NOT NULL, ADD CONSTRAINT CH_MARK CHECK (mark >=1 AND mark<=10) ;???
ALTER TABLE Subject ADD CONSTRAINT CH_grade CHECK (grade>=1 AND grade<=5);
ALTER TABLE PaymentType ADD CONSTRAINT UN_name UNIQUE(name);
ALTER TABLE Payment MODIFY type_id BIGINT NOT NULL, MODIFY amount DECIMAL NOT NULL, MODIFY payment_date DATETIME NOT NULL; ???