SELECT MIN(PAYMENT_DATE ) FROM PAYMENT ;
SELECT max(BIRTHDAY) FROM STUDENT;
SELECT AVG(MARK) FROM MARK WHERE SUBJECT_ID = (SELECT ID FROM SUBJECT WHERE NAME = 'Math');
SELECT min(AMOUNT) FROM PAYMENT WHERE TYPE_ID  = (SELECT ID FROM PAYMENTTYPE WHERE NAME = 'WEEKLY');
